services:
  backend:
    extends:
      file: compose.prod.yaml
      service: backend
    build:
      target: development
    environment:
      CLIENT_DOMAIN: ${CLIENT_DOMAIN}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt

  frontend:
    extends:
      file: compose.prod.yaml
      service: frontend
    build:
      target: development
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
